### ISSUE TITLE
What is the second arguement in "hooks" in appsettings.json

### ISSUE THREAD

**Issue by vivekgsheth** [cocowalla/serilog-sinks-file-header#6]
`{
  "Serilog": {
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "path": "log.gz",
          "hooks": "MyApp.Logging.SerilogHooks::MyHeaderWriter, **MyApp**"
        }
      }
    ]
  }
}`

**Comment by cocowalla** [comment]
We already communicated over email about this, I've pasted my response below:

The part after the comma is the **assembly name**, the part before is the **fully qualified type nam**e of your header writer class.

In the readme, directly underneath the code sample it explains:

> To break this down a bit, what you are doing is specifying the fully qualified type name of the static class that provides your HeaderWriter, using `Serilog.Settings.Configuration`'s special `::` syntax to point to the `MyHeaderWriter `member.

**Comment by vivekgsheth** [comment]
Still it is not working even after specifying the assmebly name. The first approach is working fine but I need to use the appsettings approach. Any idea what might be the issue? Or is there any other way without using "Hooks"?

**Comment by cocowalla** [comment]
You're not giving me much to go on, but my guess is that the fully-qualified type name of the header writer class is incorrect, or the assembly name is incorrect.

Few other things to look for:

1. If you're using signed assemblies, you _might_ need to include the public key in the assembly name
2. You might need to include a `Using` key in your JSON to let Serilog know about the assembly. You can see an example [here](https://github.com/serilog/serilog-settings-configuration#serilogsettingsconfiguration--)
3. If you're using .NET Framework, rather than .NET Core, see [here](https://github.com/serilog/serilog-settings-configuration#using-section-and-auto-discovery-of-configuration-assemblies)

Finally, it might help to [enable Serilog's internal diagnostic logging](https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics) - you can configure it to write to the console for example.

If you're still stuck, it would be helpful to see the csproj file for your project, and the .cs file that contains your header writer class - you can attach them to a comment here, or create a private gist and email me the link via nuget if you prefer.

**Comment by cocowalla** [comment]
I've just added another [sample project](https://github.com/cocowalla/serilog-sinks-file-header/tree/master/sample/Serilog.Sinks.File.Header.ConfigSample), which demonstrates using this library to write CSV-formatted logs with a header row, as per the readme.

I'll close this issue out for now, but you can re-open it if there is a problm.
